### ISSUE TITLE
Error since upgrading to Rspec 3

### ISSUE THREAD

**Issue by deanobarnett** [brrygrdn/database_plumber#3]
```
Failure/Error: Unable to find matching line from backtrace
        `example` is not available from within an example (e.g. an `it` block) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). It is only available on an example group (e.g. a `describe` or `context` block).
      # /Users/***/.rvm/gems/ruby-2.1.2@***/gems/actionpack-4.1.6/lib/action_dispatch/testing/assertions/routing.rb:171:in `method_missing'
      # /Users/***/.rvm/gems/ruby-2.1.2@***/gems/actionpack-4.1.6/lib/action_dispatch/testing/integration.rb:396:in `method_missing'
      # ./spec/spec_helper.rb:159:in `block (2 levels) in <top (required)>'
```

**Comment by brrygrdn** [comment]
RSpec 3 requires explicit passing of `example` in after blocks, I've updated the README accordingly in https://github.com/brrygrdn/database_plumber/commit/4b82e99acdb63e02ba81b09a207707d6b5745379
